spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/medical_documentation
    username: adminDP
    password: adminpass
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  jackson:
    default-property-inclusion: non_null
server:
  ssl:
    key-store: classpath:keystore/trustStore.p12
    key-store-password: medicalDocDP
    key-store-type: pkcs12
    key-alias: medicalDoc
    key-password: medicalDocDP
  port: 8443